### ISSUE TITLE
USERBOT

### ISSUE THREAD

**Issue by BinaryWorld0101201** [PaulSonOfLars/tgbot#44] opened 2018-08-06 18:23 UTC
You can add anti userbot storm?

**Comment by PaulSonOfLars** [comment] 2018-08-06 18:26
What? This doesnt explain what the issue is, what the expected result is, or even what you expect me to do. Clarify?

**Comment by BinaryWorld0101201** [comment] 2018-08-07 04:54
User bot telegram storm.

**Comment by Usman1329** [comment] 2018-08-07 05:55
@BinaryWorld0101201 Would be cool and less awwfull, If you tell what is the main problem and can you identify the who is user and who is user bot ? NO you can't the only i can understand from storm is spamming use flood controls and locks for urls amd other things please. Close this issue🙂

**Comment by PaulSonOfLars** [comment] 2018-08-07 07:55
Closing issue because it doesn't make sense, and the opener is unable to communicate what the issue is.

**Closed by PaulSonOfLars** 2018-08-07 07:55 UTC
